# DIPET Apache Flink  standalone
# beta v0.0.1
#
#Copyright 2019, West University of Timisoara, Timisoara, Romania
#    http://www.uvt.ro/
#Developers:
# * Gabriel Iuhasz, iuhasz.gabriel@info.uvt.ro
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at:
#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License. :

$provisioning = <<SCRIPT
#!/bin/bash

export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
apt-get update
apt-get install wget -y
apt-get install collectd -y
apt-get install python3-pip -y

sudo chown vagrant:vagrant -R /opt

cd /opt
wget https://mirror.efect.ro/apache/flink/flink-1.11.2/flink-1.11.2-bin-scala_2.12.tgz
tar -xzvf flink-1.11.2-bin-scala_2.12.tgz && cd /opt/flink-1.11.2-bin-scala_2.12.tgz
SCRIPT

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "flink_solo"
  config.vm.network "private_network", ip: "10.211.55.122"
  config.vm.network "forwarded_port", guest: 8888, host: 8897
  config.vm.network "forwarded_port", guest: 8080, host: 8081
  config.vm.network "forwarded_port", guest: 7070, host: 7070
  config.vm.network "forwarded_port", guest: 4040, host: 4040
  config.vm.network "forwarded_port", guest: 18080, host: 18080

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.name = "flink_solo"
  end

  config.vm.provision :shell, :inline => $provisioning

end